apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: idea-factory-xyz
  name: idea-factory-xyz
spec:
  replicas: 2
  selector:
    matchLabels:
      app: idea-factory-xyz
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: idea-factory-xyz
    spec:
      containers:
      - image: gcr.io/be-morisawa-toma/idea-factory-xyz
        name: nginx
        resources: {}
status: {}
