apiVersion: v1
kind: Service
metadata:
  name: idea-factory-xyz
spec:
  ports:
  - nodePort: 31935
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: idea-factory-xyz
  type: LoadBalancer
